[package]
name = "korg-nanokontrol2"
version = "0.1.0"
authors = ["Jonny Bolton <jonnybolton@gmail.com>"]
edition = "2018"

[dependencies]
midir = "0.5.0"

[lib]
name = "korgnanokontrol2"
path = "src/lib.rs"
crate-type = ["cdylib"]
